import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import "./AllCategories.css";
import {
  faBullhorn,
  faChartLine,
  faUsers,
  faEnvelope,
  faCalendarAlt,
  faSearch,
  faAd,
  faGlobe,
  faMailBulk,
  faPen,
  faLightbulb,
  faUserTie,
  faArrowAltCircleUp,
  faFileAlt,
  faPencilAlt,
  faProjectDiagram,
  faMobileAlt,
  faHandHoldingUsd,
  faCommentDollar,
  faFileContract,
  faMousePointer,
  faMobile,
  faNetworkWired,
  faBrain,
  faVirus,
  faUserCheck,
  faCodeBranch,
  faDesktop,
  faTasks,
  faRobot,
  faDatabase,
  faServer,
  faChalkboardTeacher,
  faLanguage,
  faMapMarkerAlt,
  faShippingFast,
  faPlane,
  faTools,
  faUniversity,
  faMoneyCheckAlt,
  faBuilding,
} from "@fortawesome/free-solid-svg-icons";

import {
  faPhone,
  faTruck,
  faShieldAlt,
  faCheckCircle,
  faKeyboard,
  faUser,
  faBoxOpen,
  faCog,
  faCloud,
  faBalanceScale,
  faCalculator,
  faGavel,
  faLeaf,
  faHome,
  faHeartbeat,
  faLaptopCode,
  faHeadset,
  faHandshake,
  faComments,
  faPhoneAlt,
  faCouch,
  faPalette,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCamera,
  faMusic,
  faBox,
  faSignature,
  faVideo,
  faMicrophone,
  faUserAlt,
  faPaintBrush,
  faFilePowerpoint,
  faIndustry,
  faCube,
  faMagic,
  faGamepad,
  faFilm,
  faHardHat,
  faFlask,
  faCity,
  faBolt,
  faAtom,
} from "@fortawesome/free-solid-svg-icons";

import { faBitcoin } from "@fortawesome/free-brands-svg-icons";

const categories = [
  {
    title: "Sales, Marketing, and Growth",
    items: [
      { name: "Advertising", icon: faBullhorn },
      { name: "Digital Marketing", icon: faChartLine },
      { name: "Social Media Marketing", icon: faUsers },
      { name: "Email Marketing", icon: faEnvelope },
      { name: "Event Planning", icon: faCalendarAlt },
      { name: "Search Engine Optimization (SEO)", icon: faSearch },
      { name: "Paid Ads", icon: faAd },
      { name: "Public Relations", icon: faGlobe },
      { name: "Direct Mail", icon: faMailBulk },
      { name: "Content Marketing", icon: faPen },
      { name: "Copywriting", icon: faLightbulb },
      { name: "Branding & Brand Strategy", icon: faPencilAlt },
      { name: "Influencer & Celebrity Marketing", icon: faUserTie },
      { name: "Outbound Sales & SDR", icon: faArrowAltCircleUp },
      { name: "Lead Generation", icon: faFileAlt },
      { name: "Search Engine Marketing (SEM)", icon: faMousePointer },
      { name: "Content Writing", icon: faMobile },
      { name: "Editing & Proofreading", icon: faLightbulb },
      { name: "Professional & Business Writing", icon: faNetworkWired },
      { name: "Sales & Marketing Copywriting", icon: faBrain },
      { name: "Event Marketing", icon: faVirus },
      { name: "Ecommerce Marketing & Growth", icon: faUserCheck },
      { name: "SMS & Text Marketing", icon: faCodeBranch },
      { name: "Marketing Strategy", icon: faDesktop },
      { name: "Mobile App Marketing", icon: faTasks },
      { name: "Growth Hacking", icon: faRobot },
      { name: "Conversion Rate Optimization (CRO)", icon: faNetworkWired },
      { name: "Account-Based Marketing (ABM)", icon: faDatabase },
    ],
  },
  {
    title: "Development, Technology, and Software",
    items: [
      { name: "Mobile App Development", icon: faMobileAlt },
      { name: "Web Development", icon: faHandHoldingUsd },
      { name: "Artificial Intelligence (AI)", icon: faCommentDollar },
      { name: "Augmented Reality (AR/VR)", icon: faFileContract },
      { name: "Software Development", icon: faMousePointer },
      { name: "Cybersecurity", icon: faMobile },
      { name: "User Testing", icon: faLightbulb },
      { name: "User Experience (UX/UI)", icon: faNetworkWired },
      { name: "Information Technology (IT)", icon: faBrain },
      { name: "Engineering", icon: faVirus },
      { name: "Ecommerce Development", icon: faUserCheck },
      { name: "Blockchain Development", icon: faCodeBranch },
      { name: "Desktop Application Development", icon: faDesktop },
      { name: "Product Management", icon: faTasks },
      { name: "Software Automation & Scripts", icon: faRobot },
      { name: "Mobile App Design", icon: faNetworkWired },
      { name: "Game Design & Development", icon: faDatabase },
      { name: "Emerging Tech", icon: faServer },
      { name: "Geo Info Systems (GIS) Development", icon: faChalkboardTeacher },
      { name: "Information Security & Compliance", icon: faLanguage },
      { name: "Database Management & Admin", icon: faMapMarkerAlt },
      { name: "Network & System Administration", icon: faShippingFast },
      { name: "DevOps", icon: faPlane },
      { name: "Solution Architecture", icon: faTools },
      { name: "Web Design", icon: faUniversity },
      { name: "IoT Development", icon: faMoneyCheckAlt },
      { name: "Cloud Computing", icon: faBuilding },
    ],
  },
  {
    title: "Sales, Marketing, and Growth",
    items: [
      { name: "Advertising", icon: faBullhorn },
      { name: "Digital Marketing", icon: faChartLine },
      { name: "Social Media Marketing", icon: faUsers },
      { name: "Email Marketing", icon: faEnvelope },
      { name: "Event Planning", icon: faCalendarAlt },
      { name: "Search Engine Optimization (SEO)", icon: faSearch },
      { name: "Paid Ads", icon: faAd },
      { name: "Public Relations", icon: faGlobe },
      { name: "Direct Mail", icon: faMailBulk },
      { name: "Content Marketing", icon: faPen },
      { name: "Copywriting", icon: faLightbulb },
      { name: "Branding & Brand Strategy", icon: faPencilAlt },
      { name: "Influencer & Celebrity Marketing", icon: faUserTie },
      { name: "Outbound Sales & SDR", icon: faArrowAltCircleUp },
      { name: "Lead Generation", icon: faFileAlt },
      { name: "Search Engine Marketing (SEM)", icon: faMousePointer },
      { name: "Content Writing", icon: faMobile },
      { name: "Editing & Proofreading", icon: faLightbulb },
      { name: "Professional & Business Writing", icon: faNetworkWired },
      { name: "Sales & Marketing Copywriting", icon: faBrain },
      { name: "Event Marketing", icon: faVirus },
      { name: "Ecommerce Marketing & Growth", icon: faUserCheck },
      { name: "SMS & Text Marketing", icon: faCodeBranch },
      { name: "Marketing Strategy", icon: faDesktop },
      { name: "Mobile App Marketing", icon: faTasks },
      { name: "Growth Hacking", icon: faRobot },
      { name: "Conversion Rate Optimization (CRO)", icon: faNetworkWired },
      { name: "Account-Based Marketing (ABM)", icon: faDatabase },
    ],
  },
  {
    title: "Development, Technology, and Software",
    items: [
      { name: "Mobile App Development", icon: faMobileAlt },
      { name: "Web Development", icon: faHandHoldingUsd },
      { name: "Artificial Intelligence (AI)", icon: faCommentDollar },
      { name: "Augmented Reality (AR/VR)", icon: faFileContract },
      { name: "Software Development", icon: faMousePointer },
      { name: "Cybersecurity", icon: faMobile },
      { name: "User Testing", icon: faLightbulb },
      { name: "User Experience (UX/UI)", icon: faNetworkWired },
      { name: "Information Technology (IT)", icon: faBrain },
      { name: "Engineering", icon: faVirus },
      { name: "Ecommerce Development", icon: faUserCheck },
      { name: "Blockchain Development", icon: faCodeBranch },
      { name: "Desktop Application Development", icon: faDesktop },
      { name: "Product Management", icon: faTasks },
      { name: "Software Automation & Scripts", icon: faRobot },
      { name: "Mobile App Design", icon: faNetworkWired },
      { name: "Game Design & Development", icon: faDatabase },
      { name: "Emerging Tech", icon: faServer },
      { name: "Geo Info Systems (GIS) Development", icon: faChalkboardTeacher },
      { name: "Information Security & Compliance", icon: faLanguage },
      { name: "Database Management & Admin", icon: faMapMarkerAlt },
      { name: "Network & System Administration", icon: faShippingFast },
      { name: "DevOps", icon: faPlane },
      { name: "Solution Architecture", icon: faTools },
      { name: "Web Design", icon: faUniversity },
      { name: "IoT Development", icon: faMoneyCheckAlt },
      { name: "Cloud Computing", icon: faBuilding },
    ],
  },
  {
    title: "AI, Data Science, & Analytics",
    items: [
      { name: "Market Research", icon: faSearch },
      { name: "Analytics", icon: faChartLine },
      { name: "Artificial Intelligence (AI)", icon: faBrain },
      { name: "Data Testing", icon: faCodeBranch },
      { name: "Business Intelligence", icon: faLightbulb },
      { name: "Data Operations", icon: faDatabase },
      { name: "Database Management & Admin", icon: faMapMarkerAlt },
      { name: "Big Data", icon: faServer },
      { name: "Data Science", icon: faVirus },
      { name: "Predictive Analytics", icon: faFileAlt },
      { name: "MLOps", icon: faNetworkWired },
    ],
  },
  {
    title: "Administrative and Operations",
    items: [
      { name: "Recruiting", icon: faUsers },
      { name: "Call Centers", icon: faPhone },
      { name: "Administrative", icon: faFileAlt },
      { name: "Outbound Sales & SDR", icon: faArrowAltCircleUp },
      { name: "Transcription", icon: faFileAlt },
      { name: "Freight & Trucking", icon: faTruck },
      { name: "Real Estate (Commercial)", icon: faBuilding },
      { name: "3rd Party Logistics (3PL)", icon: faShippingFast },
      { name: "Security & Bodyguards", icon: faShieldAlt },
      { name: "Sales Coaching & Training", icon: faChalkboardTeacher },
      { name: "CRM Optimization, Implementation, & Management", icon: faUserCheck },
      { name: "Quality Assurance (QA) and Testing", icon: faCheckCircle },
      { name: "Lead Generation", icon: faFileAlt },
      { name: "Data Entry", icon: faKeyboard },
      { name: "Project Management", icon: faProjectDiagram },
      { name: "Virtual Assistance", icon: faUser },
      { name: "Language Tutoring & Interpretation", icon: faLanguage },
      { name: "Translation & Localization Services", icon: faGlobe },
      { name: "Writing", icon: faPen },
      { name: "Human Resources (HR)", icon: faUsers },
      { name: "DevOps", icon: faPlane },
      { name: "Staffing", icon: faUsers },
      { name: "Fulfillment", icon: faBoxOpen },
      { name: "Shipping", icon: faShippingFast },
      { name: "Travel Planning", icon: faPlane },
      { name: "Remote Office Management", icon: faDesktop },
      { name: "Process Automation", icon: faRobot },
    ],
  },
  {
    title: "Consulting, Management, Accounting, and Legal",
    items: [
      { name: "Market Research", icon: faSearch },
      { name: "Strategic Consulting", icon: faChartLine },
      { name: "Operational Consulting", icon: faCog },
      { name: "Management Consulting", icon: faUserTie },
      { name: "Cloud Consulting", icon: faCloud },
      { name: "Analytics", icon: faChartLine },
      { name: "Financial Advisory", icon: faCommentDollar },
      { name: "Investment Management", icon: faHandHoldingUsd },
      { name: "Business & Corporate Law", icon: faBalanceScale },
      { name: "Accounting", icon: faCalculator },
      { name: "Information Technology (IT)", icon: faDesktop },
      { name: "Venture Capital", icon: faLightbulb },
      { name: "International Law", icon: faGlobe },
      { name: "Public Law", icon: faGavel },
      { name: "Private Law", icon: faGavel },
      { name: "Bookkeeping", icon: faFileAlt },
      { name: "Regulatory Law", icon: faGavel },
      { name: "Professional Coaching", icon: faUsers },
      { name: "Finance", icon: faMoneyCheckAlt },
      { name: "Information Security & Compliance", icon: faShieldAlt },
      { name: "Sustainability Consulting", icon: faLeaf },
      { name: "Property Law", icon: faHome },
      { name: "Legal Support Services", icon: faGavel },
      { name: "Labor Law", icon: faBalanceScale },
      { name: "Health Law", icon: faHeartbeat },
      { name: "Digital Transformation", icon: faLaptopCode },
      { name: "Cryptocurrency Regulation", icon: faBitcoin },
    ],
  },
  {
    title: "Customer Service & Relations",
    items: [
      { name: "Call Centers", icon: faPhone },
      { name: "Tech Support", icon: faHeadset },
      { name: "Customer Engagement & Success", icon: faHandshake },
      { name: "Community Management", icon: faUsers },
      { name: "Customer Service & Support", icon: faComments },
      { name: "Data Entry", icon: faKeyboard },
      { name: "Virtual Assistance", icon: faUser },
      { name: "Omnichannel Support", icon: faPhoneAlt },
      { name: "Customer Experience Design", icon: faLightbulb },
      { name: "AI Chatbots", icon: faRobot },
    ],
  },
  {
    title: "Design & Creative",
    items: [
      { name: "Social Media Marketing", icon: faUsers },
      { name: "Interior Design", icon: faCouch },
      { name: "Graphic Design", icon: faPalette },
      { name: "Corporate Photography", icon: faCamera },
      { name: "Audio, Sound, & Music Production", icon: faMusic },
      { name: "Package Design", icon: faBox },
      { name: "Naming", icon: faSignature },
      { name: "Branding & Brand Strategy", icon: faPencilAlt },
      { name: "Video Production", icon: faVideo },
      { name: "Voiceover", icon: faMicrophone },
      { name: "User Experience (UX/UI)", icon: faUserAlt },
      { name: "Art & Illustration", icon: faPaintBrush },
      { name: "Editorial & Presentation Design", icon: faFilePowerpoint },
      { name: "Product & Industrial Design", icon: faIndustry },
      { name: "3D Modeling & CAD", icon: faCube },
      { name: "Animation", icon: faMagic },
      { name: "Trade Show & Conference Design", icon: faBuilding },
      { name: "Mobile App Design", icon: faMobileAlt },
      { name: "Game Design & Development", icon: faGamepad },
      { name: "Logo Design", icon: faSignature },
      { name: "Creative Direction", icon: faLightbulb },
      { name: "Web Design", icon: faDesktop },
      { name: "UX/UI Design", icon: faUserAlt },
      { name: "Motion Graphics", icon: faFilm },
    ],
  },
  {
    title: "Engineering, Sciences, and Architecture",
    items: [
      { name: "Interior Design", icon: faCouch },
      { name: "Architecture (Commercial)", icon: faBuilding },
      { name: "3D Modeling & CAD", icon: faCube },
      { name: "Chemical Engineering", icon: faFlask },
      { name: "Civil & Structural Engineering", icon: faCity },
      { name: "Electrical & Electronic Engineering", icon: faBolt },
      { name: "Energy & Mechanical Engineering", icon: faCog },
      { name: "Trade Show & Conference Design", icon: faBuilding },
      { name: "Physical Sciences", icon: faAtom },
      { name: "Contract Manufacturing", icon: faIndustry },
      { name: "Product Development & Design", icon: faTools },
      { name: "Building Engineering", icon: faHardHat },
    ],
  },
  // Add more categories as needed
];

const AllCategories = () => {
  return (
    <div className="categories-container">
      {categories.map((category, index) => (
        <div key={index} className="category">
          <h2>{category.title}</h2>
          <div className="category-items">
            {category.items.map((item, idx) => (
              <div key={idx} className="category-item">
                <FontAwesomeIcon icon={item.icon} size="2x" />
                <span>{item.name}</span>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
};

export default AllCategories;
